### ISSUE TITLE
Lexical or Preprocessor Issue Hoa.hpp file not found

### ISSUE THREAD

**Issue by nightshining** [CICM/ofxHoa#1]
Hi there,
I built an empty project from the openframeworks generator, inserted the ofxHoa addon via the OF plugin but I seem to be getting a 'file not found' 'Lexical or Preprocessor' issue in Xcode 6.2 running in latest Yosemite and OF 8.4. I added the correct file path to the Hoa.hpp file in xcode's 'Search Library' and 'Search Headers' Path, cleaned the project and ran again but still failing to build. Also, I have the /Sources folder inside ofxHoa/libs/HoaLibrary-Light. My project contains exactly the code from the '3d' demo that was included with the addon (which runs perfectly ), in this case I copied it over. Thank you in advance. 

![screen shot 2015-04-13 at 3 31 26 pm](https://cloud.githubusercontent.com/assets/6088743/7123732/399c8d78-e1f2-11e4-88f4-4b6ef092cb6d.png)

![screen shot 2015-04-13 at 3 41 20 pm](https://cloud.githubusercontent.com/assets/6088743/7123934/92fd3cea-e1f3-11e4-99ba-03492f978f72.png)

**Comment by claudiocabral** [comment]
Hi, I'm updating my OS right now so I'll only be able to look at it in the
morning, but: ofxHoa uses a gitsubmodule of yhe Hoa Library. If you've
downloaded it as a .zip from the site, the submodule will be missing.
Please download it and put it in te correct folder (libs/HoaLibrary-Light
if I recall from memory).  That is not problem, please tell me and I'll
look into it tomorrow. Other then that, it has not been officialy released,
so some bugs may be present.
Em 13/04/2015 21:39, "Mike Romeo" notifications@github.com escreveu:

**Comment by pierreguillot** [comment]
The problem should be solved.
Thx

**Comment by nightshining** [comment]
Thanks so much! Works fine now.
