### ISSUE TITLE
Binaural Decoding

### ISSUE THREAD

**Issue by garrettburnett** [CICM/ofxHoa#2]
In the examples, it instructs us to choose which decoder we would like to use by commenting out the 2 options. 
![image](https://cloud.githubusercontent.com/assets/14268490/10126174/63078424-6541-11e5-8797-aa401dc8f14a.png)

When i choose binaural decoding, I ultimately get no sound at all. Is there something I'm missing?

**Comment by pierreguillot** [comment]
Hi,
For binaural, you should use "processBlock" method instead of "process" method : 
(static_cast<Decoder<Hoa3d, t_sample>::Binaural_>(decoder))->processBlock((const float_*)ins, outs);
with "ins" and "outs" the samples matrices (number of channels \* block size)

**Comment by garrettburnett** [comment]
sorry, I'm a little confused. Where exactly should I put this in my code?

**Comment by pierreguillot** [comment]
Here what must change:

```
void ofApp::setup(){
...
harmonicsMatrix = new float[order*2+1][bufferSize];
outputMatrix = new float[2][bufferSize];
...
}

void ofApp::audioOut( float * output, int bufferSize, int nChannels){

    for (int i = 0; i<bufferSize; i++) {

        hoaCoord->process();
        input = myOsc.tick()*(myEnv.tick()+1)*0.05;
        hoaEncoder->setRadius(hoaCoord->getRadius(0));
        hoaEncoder->setAzimuth(hoaCoord->getAzimuth(0));
        hoaEncoder->process(&input, harmonicsBuffer[i]);
        hoaOptim->process(harmonicsBuffer, harmonicsBuffer);
        for (int j = 0; j<order*2+1; j++) {
             harmonicsMatrix[j][i] = harmonicsBuffer[j];
             }
        }
    (static_cast::Binaural>(hoaDecoder))->processBlock(harmonicsMatrix, outputMatrix);
    for (int i = 0; i<bufferSize; i++) {
    output[i*nChannels] = outputMatrix[0][i];
    output[i*nChannels+1] = outputMatrix[1][i];
    }   
}
```

I didn't try the code (perhaps that the samples of the output vector are not interleaved). 
We optimize by computing the binaural rendering for a matrix of samples instead of several vectors of samples.

**Comment by garrettburnett** [comment]
I'm having a few issues with this as well unfortunately. I still get no sound.

**Comment by pierreguillot** [comment]
You should have a look at the binaural example (you should just keep in mind that in 3D there are (order+1)^2 harmonics (instead of order*2+1). Or if you show me your code, I could try to figure out what is going wrong if you want.

**Comment by garrettburnett** [comment]
Hi, 

Here is my .h and .cpp file where I'm handling all of the hoa stuff:

#pragma once
#include "ofMain.h"
#include "orb.h"
#include "GUI.h"
//#include "ofxOculusDK2.h"
#include "ofxHoa.h"
#include "ofxStk.h"

using namespace hoa;

class ofApp : public ofBaseApp{

public:
    void setup();
    void update();
    void draw();

```
void keyPressed(int key);
void keyReleased(int key);
void mouseMoved(int x, int y );
void mouseDragged(int x, int y, int button);
void mousePressed(int x, int y, int button);
void mouseReleased(int x, int y, int button);
void windowResized(int w, int h);
void dragEvent(ofDragInfo dragInfo);
void gotMessage(ofMessage msg);
void audioOut(float *output,int bufferSize,int nChannels);

int getselX();
int getselY();
int getselZ();

ofCamera cam;
ofLight light;

vector <orb> orbs;

float camx,camy,camz;
float selX=0,selY=0,selZ=0;
float selRad =1;

GUI gui;
//sound//
int nOutputs, nInputs, sampleRate, bufferSize, nBuffers;
ofSoundStream stream;
```

   static int const hoaOrder = 1;
   static int const numberOfParticles=10;

```
float * harmonic;
float * input;
float binInput;

float harmonicsBuffer[7];

float * * harmonicMatrix;
float * outputMatrix;

//setup a 3D encoder.
Encoder<Hoa3d, float>::Multi * encoder;
Decoder<Hoa3d, float> * decoderReg;
```

   Decoder<Hoa3d, float>::Binaural \* decoder = new Decoder<Hoa3d, float>::Binaural(hoaOrder);

```
Optim<Hoa3d, float>::Basic * optim;
ofxHoaCoord<Hoa3d, float> * hoaCoord;

stk::Clarinet file[numberOfParticles];
```

};

and my .cpp file:

#include "ofApp.h"
//--------------------------------------------------------------
void ofApp::setup(){

```
ofBackground(0);
ofEnableDepthTest();
ofSetFrameRate(60);
camx=0;
camy=0;
camz=0;

ofEnableSmoothing();
cam.setVFlip(true);
cam.lookAt(ofVec3f(0,0,-10));
cam.setNearClip(0);
//light setup//
cam.setPosition(ofVec3f(camx,camy,camz));
light.setPosition(10,-20,0);
light.enable();

ofToggleFullscreen();

//sound//
nOutputs = 2;
nInputs = 0;
sampleRate = 44100;
bufferSize = 512;
nBuffers = (nOutputs+nInputs)*2;

 stk::Stk::setSampleRate(44100.0);
hoaOrder;

harmonic = new float[(hoaOrder+1)*(hoaOrder+1)];
input =new float[numberOfParticles];
binInput = 0;
```

//memset(harmonic, 0, sizeof(float)_(hoaOrder+1)_(hoaOrder+1));
//memset(input, 0, sizeof(float)*10);

```
encoder = new Encoder<Hoa3d, float>::Multi(hoaOrder, numberOfParticles); //100 sources for now.

//Regular Decoder//
decoderReg = new Decoder<Hoa3d, float>::Regular(hoaOrder,nOutputs);
decoderReg->computeRendering(bufferSize);


decoder = new Decoder<Hoa3d, float>::Binaural(hoaOrder);
decoder->setCropSize(256);
decoder->computeRendering(bufferSize);

optim = new Optim<Hoa3d, float>::Basic(hoaOrder);

// CREATE HOACOORD AND SET RAMP IN MILLISECONDS
hoaCoord = new ofxHoaCoord<Hoa3d, float>(numberOfParticles);
hoaCoord->setRamp(50, sampleRate);

// SET SPATIAL REFERENCE
hoaCoord->setAmbisonicRadius(10000);
hoaCoord->setAmbisonicCenter(ofVec3f(0,0,0));
stream.setup(this, nOutputs, nInputs, sampleRate, bufferSize, nBuffers);

for(int i=0;i<numberOfParticles;i++){
```

//        file[i].openFile(ofToDataPath("A4.wav",true));
         file[i].noteOn(i*300, 1);
    }

```
//for binaural//
```

}

//--------------------------------------------------------------
void ofApp::update(){
    for(int i=0;i<orbs.size();i++){
        orbs[i].update(ofVec3f(selX,selY,selZ), orbs, gui.mode);
        hoaCoord->setSourcePositionDirect(i, orbs[i].position);//sets the respective position for each orb and sound source. Pairs them.
    }
   gui.update();
}
//--------------------------------------------------------------
void ofApp::draw(){
    //This will be the starting of a GUI//

```
cam.begin();

    for(int i=0;i<orbs.size();i++)
    {
    orbs[i].draw();
    }

ofSetColor(255, 255, 255);
ofNoFill();
ofSetSphereResolution(10);
ofDrawSphere(selX,selY,selZ, selRad);
ofPushMatrix();
ofRotate(90, 0, 0, -1);
ofTranslate(0, 0, 0);
ofDrawGridPlane(500.0f, 10.0f, false );
ofPopMatrix();

cam.end();

gui.draw(selX,selY,selZ);
```

}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
    switch (key) {
        case ' ':
        {   orb tempOrb;
            tempOrb.setup(selX,selY,selZ,selRad);
            orbs.push_back(tempOrb);//using vector
        }
            break;

```
    case OF_KEY_LEFT:
    {
        selX=selX-100;

    }
        break;

    case OF_KEY_RIGHT:
    {
        selX=selX+100;

    }
        break;

    case 'w':
    {
        selY=selY-.1;
    }
        break;
    case 's':
    {
        selY=selY+.1;
    }
        break;


    case OF_KEY_UP:
    {
        selZ=selZ-100;

    }
        break;

    case OF_KEY_DOWN:
    {
        selZ=selZ+100 ;

    }
        break;

    case '[':
    {
        selRad=selRad-.1;
    }
        break;
    case ']':
    {
        selRad=selRad+.1;
    }
        break;

    case 'u':
    {
        gui.mode=GUI::STILL;
    }
        break;
    case 'i':
    {
        gui.mode=GUI::DISPERSE;
    }
        break;
    case 'o':
    {
        gui.mode=GUI::FISH;
    }
        break;
    default:
        break;
}
```

}

//--------------------------------------------------------------
void ofApp::keyReleased(int key){

}

//--------------------------------------------------------------
void ofApp::mouseMoved(int x, int y ){

}

//--------------------------------------------------------------
void ofApp::mouseDragged(int x, int y, int button){

}

//--------------------------------------------------------------
void ofApp::mousePressed(int x, int y, int button){

}

//--------------------------------------------------------------
void ofApp::mouseReleased(int x, int y, int button){

}

//--------------------------------------------------------------
void ofApp::windowResized(int w, int h){

}

//--------------------------------------------------------------
void ofApp::gotMessage(ofMessage msg){

}

//--------------------------------------------------------------
void ofApp::dragEvent(ofDragInfo dragInfo){

}
void ofApp::audioOut(float *output, int bufferSize, int nChannels){

```
//REGULAR MODE//
for (int i = 0; i < bufferSize ; i++) {
     hoaCoord->process();

    for(int j=0;j<numberOfParticles;j++)
    {
        input[j] = (file[j].tick()/numberOfParticles)*0.3;

        //set radius, azimuth, and elevation.
        encoder->setRadius(j, hoaCoord->getRadius(j));
        encoder->setAzimuth(j, hoaCoord->getAzimuth(j));
        encoder->setElevation(j, hoaCoord->getElevation(j));
    }

    encoder->process(input,harmonic);

    optim->process(harmonic, harmonic);

     decoderReg->process(harmonic, output+i*nChannels);
}
```

}

**Comment by pierreguillot** [comment]
The problem comes from the processBlock method of the binaural decoder that expects a matrix of harmonics [number of harmonics][buffer size] and a matrix of output signals [2][buffer size]

Here the hpp:

```
class ofApp : public ofBaseApp{
...
private:
float** harmonicMatrix;
float*  outputMatrix[2];
...
}
```

Here the cpp:

```
void ofApp::setup(){
...
  decoder = new Decoder<Hoa3d, float>::Binaural(hoaOrder);
  decoder->setCropSize(256);
  decoder->computeRendering(bufferSize);
  harmonicMatrix = new float * [(hoaOrder+1)*(hoaOrder+1) ];
  for(int i = 0; i < (hoaOrder+1)*(hoaOrder+1); i++) 
      harmonicMatrix[i] = new float[bufferSize];
  outputMatrix[0] = new float[bufferSize];
  outputMatrix[1] = new float[bufferSize];
...
}
```

```
void ofApp::audioOut(float * output, int bufferSize, int nChannels){

    for(int i = 0; i < bufferSize; i++) {
       for(int j = 0; j < numberOfParticles ;j++) {
         input[j] = (file[j].tick()/numberOfParticles)*0.3;
         encoder->setRadius(j, hoaCoord->getRadius(j));
         encoder->setAzimuth(j, hoaCoord->getAzimuth(j));
         encoder->setElevation(j, hoaCoord->getElevation(j));
      }
      encoder->process(input,harmonic);
      for (int j = 0; j < (hoaOrder+1)*(hoaOrder+1); j++)
            harmonicMatrix[j][i] = harmonicsBuffer[j];
    }
    decoder.processBlock(const_cast<const float **>(harmonicMatrix), outputMatrix);

    for (int i = 0; i < bufferSize; i++) {
        output[i*nChannels] = outputMatrix[0][i];
        output[i*nChannels+1] = outputMatrix[1][i];
    }
}
```

PS : If you really want to have a static order and a static number of particles, you can avoid most of the dynamic allocations.

**Comment by garrettburnett** [comment]
Hi, even with that I still do not get sound. 

Here is my code: https://github.com/garrettburnett/Thesis
