### ISSUE TITLE
Does not work with project generator - Eigen includes

### ISSUE THREAD

**Issue by fred-dev** [CICM/ofxHoa#5]
I have tried to make this addon work with the current openframeworks and the project generator. It seems there are quite a few issues. The included project files also do not work. Are there any plans to update this? It seems that the hoa library relies on Eigen, but to get things going it would require updating to Eigen3. Any info on how to get this working would be great.

**Comment by claudiocabral** [comment]
Hi @fred-dev,
I was the developer on this project a couple of years ago, but it's been a while since I worked with this team. As it is, ofxHoa is unmaintained and most likely unusable.
I don't know if @CICM/hoa has any plans for it, but I don't think so.
